### ISSUE TITLE
TypeError: Cannot read property 'getDatabaseAccount' of undefined

### ISSUE THREAD

**Issue by TsuyoshiUshio** [jcormont/documentdb-typescript#14]
I've got the error, when I use `getAccountInfoAsync`. Other method works. 

To reproduce,  I just install this npm

```
$ npm install documentdb-typescript --save
httptriggerjs@1.0.0 /Users/ushio/Codes/musclehack/spike/HttpTriggerJS
└─┬ documentdb-typescript@1.0.6 
  └─┬ documentdb@1.12.2 
    ├── binary-search-bounds@2.0.3 
    ├── priorityqueuejs@1.0.0 
    ├── semaphore@1.0.5 
    └── underscore@1.8.3 
```

then create this ts file.

```ts
import * as DB from "documentdb-typescript";

async function main() {
    const client = new DB.Client("MY_COSMOS_HOST","MY_KEY");
    // enable logging of all operations to the console
    client.enableConsoleLog = true;
    
       // dump the account information
       console.log(await client.getAccountInfoAsync());
    
       // open the connection and print a list of IDs
       await client.openAsync();
       var dbs = await client.listDatabasesAsync();
       console.log(dbs.map(db => db.id));
    
       // unnecessary unless you expect new clients
       // to reopen the connection:
       client.close();
}

main();
```

Once, I comment out ` console.log(await client.getAccountInfoAsync());`  It works well. 

Any Ideas?

**Comment by jcormont** [comment]
Try moving the `await client.openAsync();` statement up to the top of the function. The `getAccountInfoAsync` method needs the connection to be open to get its data, so you'll need to run `openAsync` _first_.

As for the TypeError, this definitely isn't very elegant and we're probably missing a check for `undefined` somewhere... I'll look into this. Thanks!

**Comment by TsuyoshiUshio** [comment]
Thank you @jcormont it makes sense. 
Then , however, the problem is, the README. I just follow your README. 
I sent a pull request for your README. [Fix This sample doesn't work. openAsync should come first than client… #15](https://github.com/jcormont/documentdb-typescript/pull/15). This npm is great! Thank you for your sharing!
