### ISSUE TITLE
Compile error with `noImplicitAny`

### ISSUE THREAD

**Issue by jahewson** [jcormont/documentdb-typescript#7]
When using the `noImplicitAny` compiler flag, the following compiler error occurs:

```
node_modules/documentdb-typescript/typings/_DocumentDB.d.ts(26,36): error TS7006: Parameter 'string' implicitly has an 'any' type.
node_modules/documentdb-typescript/typings/_DocumentDB.d.ts(27,37): error TS7006: Parameter 'string' implicitly has an 'any' type.
```

**Comment by jahewson** [comment]
Also you should probably add `noImplicitAny: true` to your tsconfig, to ensure that your library remains compatible with downstream users who have that option enabled.

**Comment by jcormont** [comment]
Thanks, done. Also added `strictNullChecks` for good measure. This has helped me avoid a load of bugs in other projects. TypeScript is awesome!
Fixed in v.1.0.0.
