### ISSUE TITLE
typescript should be in devDependencies

### ISSUE THREAD

**Issue by jahewson** [jcormont/documentdb-typescript#8]
Right now the build scripts use the system version of `tsc`, which might not be what you want. For example, I don't have `tsc` installed globally at all.

If you add `typescript` to devDependencies then npm will automatically use the corresponding `tsc` binary in `node_modules/.bin`, so you can control the exact version of the TypeScript compiler.

**Comment by jcormont** [comment]
Thanks for your suggestion, you are absolutely right about this.
Fixed in v1.0.0 now.
