### ISSUE TITLE
Support enableCrossPartitionQuery (and other options) in queryDocuments interface

### ISSUE THREAD

**Issue by sgarciac** [jcormont/documentdb-typescript#9]
The queryDocuments implementation in Collection only supports batchSize. There should be a way to pass other options, or at least enableCrossPartitionQuery.

**Comment by jcormont** [comment]
Thanks for highlighting this issue. Didn't even know this option existed because it is not in the docs for the Node.js API...

I have added  an `options` argument to most methods to allow passing feed and/or request options to the underlying API.

This is now available in v1.0.0.
